#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "hardware/i2c.h"

#ifndef APP_ENABLE_WIFI_TASK
#define APP_ENABLE_WIFI_TASK 1
#endif

#ifndef APP_ENABLE_DIMMER_TASK
#define APP_ENABLE_DIMMER_TASK 1
#endif

#ifndef APP_ENABLE_ADP910_TASK
#define APP_ENABLE_ADP910_TASK 1
#endif

#ifndef APP_ENABLE_DEBUG_HTTP_ROUTES
#define APP_ENABLE_DEBUG_HTTP_ROUTES 0
#endif

#ifndef APP_FIRMWARE_VERSION
#define APP_FIRMWARE_VERSION "0.0.0-dev"
#endif

#ifndef APP_WIFI_TASK_STACK_WORDS
#define APP_WIFI_TASK_STACK_WORDS 4096u
#endif

#ifndef APP_DIMMER_TASK_STACK_WORDS
#define APP_DIMMER_TASK_STACK_WORDS 1024u
#endif

#ifndef APP_ADP910_TASK_STACK_WORDS
#define APP_ADP910_TASK_STACK_WORDS 2048u
#endif

#ifndef APP_WIFI_TASK_PRIORITY
#define APP_WIFI_TASK_PRIORITY 2u
#endif

#ifndef APP_DIMMER_TASK_PRIORITY
#define APP_DIMMER_TASK_PRIORITY 3u
#endif

#ifndef APP_ADP910_TASK_PRIORITY
#define APP_ADP910_TASK_PRIORITY 1u
#endif

#ifndef APP_ADP910_SAMPLE_PERIOD_MS
#define APP_ADP910_SAMPLE_PERIOD_MS 20u
#endif

#ifndef APP_ADP910_LOG_EVERY_N_CYCLES
#define APP_ADP910_LOG_EVERY_N_CYCLES 0u
#endif

#ifndef APP_ADP910_I2C_FREQUENCY_HZ
#define APP_ADP910_I2C_FREQUENCY_HZ 100000u
#endif

#ifndef APP_ADP910_I2C_ADDRESS
#define APP_ADP910_I2C_ADDRESS 0x25u
#endif

#ifndef APP_ADP910_FAN_SENSOR_I2C_INSTANCE
#define APP_ADP910_FAN_SENSOR_I2C_INSTANCE i2c0
#endif

#ifndef APP_ADP910_FAN_SENSOR_SDA_PIN
#define APP_ADP910_FAN_SENSOR_SDA_PIN 4u
#endif

#ifndef APP_ADP910_FAN_SENSOR_SCL_PIN
#define APP_ADP910_FAN_SENSOR_SCL_PIN 5u
#endif

#ifndef APP_ADP910_ENVELOPE_SENSOR_I2C_INSTANCE
#define APP_ADP910_ENVELOPE_SENSOR_I2C_INSTANCE i2c1
#endif

#ifndef APP_ADP910_ENVELOPE_SENSOR_SDA_PIN
#define APP_ADP910_ENVELOPE_SENSOR_SDA_PIN 6u
#endif

#ifndef APP_ADP910_ENVELOPE_SENSOR_SCL_PIN
#define APP_ADP910_ENVELOPE_SENSOR_SCL_PIN 7u
#endif

#define APP_CONTROL_PRESSURE_SOURCE_ENVELOPE 0u
#define APP_CONTROL_PRESSURE_SOURCE_FAN 1u
#define APP_CONTROL_PRESSURE_SOURCE_AUTO_MIN_ABS 2u

#ifndef APP_CONTROL_PRESSURE_SOURCE_MODE
#define APP_CONTROL_PRESSURE_SOURCE_MODE APP_CONTROL_PRESSURE_SOURCE_ENVELOPE
#endif

#ifndef APP_FAN_PRESSURE_TO_SPEED_GAIN
#define APP_FAN_PRESSURE_TO_SPEED_GAIN 1.0f
#endif

#ifndef APP_AIR_LEAKAGE_GAIN
#define APP_AIR_LEAKAGE_GAIN 1.0f
#endif

#ifndef APP_CONTROL_TARGET_PRESSURE_PA
#define APP_CONTROL_TARGET_PRESSURE_PA 50.0f
#endif

#ifndef APP_CONTROL_PD_KP
#define APP_CONTROL_PD_KP 0.18f
#endif

#ifndef APP_CONTROL_PD_KD
#define APP_CONTROL_PD_KD 0.008f
#endif

#ifndef APP_CONTROL_PID_KI
#define APP_CONTROL_PID_KI 0.004f
#endif

#ifndef APP_CONTROL_PD_DEADBAND_PA
#define APP_CONTROL_PD_DEADBAND_PA 1.2f
#endif

#ifndef APP_CONTROL_MAX_STEP_PERCENT
#define APP_CONTROL_MAX_STEP_PERCENT 0.25f
#endif

#ifndef APP_CONTROL_MAX_STEP_UP_PERCENT
#define APP_CONTROL_MAX_STEP_UP_PERCENT APP_CONTROL_MAX_STEP_PERCENT
#endif

#ifndef APP_CONTROL_MAX_STEP_DOWN_PERCENT
#define APP_CONTROL_MAX_STEP_DOWN_PERCENT 0.35f
#endif

#ifndef APP_CONTROL_LOOP_PERIOD_MS
#define APP_CONTROL_LOOP_PERIOD_MS 20u
#endif

#ifndef APP_CONTROL_STARTUP_MIN_HOLD_MS
#define APP_CONTROL_STARTUP_MIN_HOLD_MS 80u
#endif

#ifndef APP_CONTROL_STARTUP_FULL_POWER_HOLD_MS
#define APP_CONTROL_STARTUP_FULL_POWER_HOLD_MS 300u
#endif

#ifndef APP_CONTROL_STARTUP_TARGET_RATIO
#define APP_CONTROL_STARTUP_TARGET_RATIO 0.75f
#endif

#ifndef APP_CONTROL_STARTUP_MAX_OVERSHOOT_RATIO
#define APP_CONTROL_STARTUP_MAX_OVERSHOOT_RATIO 1.01f
#endif

#ifndef APP_CONTROL_MEASUREMENT_FILTER_ALPHA
#define APP_CONTROL_MEASUREMENT_FILTER_ALPHA 0.07f
#endif

#ifndef APP_CONTROL_DERIVATIVE_CLAMP_PA_PER_S
#define APP_CONTROL_DERIVATIVE_CLAMP_PA_PER_S 25.0f
#endif

#ifndef APP_CONTROL_STEP_NEAR_TARGET_RATIO
#define APP_CONTROL_STEP_NEAR_TARGET_RATIO 0.12f
#endif

#ifndef APP_CONTROL_STEP_FAR_ERROR_PA
#define APP_CONTROL_STEP_FAR_ERROR_PA 20.0f
#endif

#ifndef APP_CONTROL_LEARNING_WINDOW_MS
#define APP_CONTROL_LEARNING_WINDOW_MS 12000u
#endif

#ifndef APP_CONTROL_LEARNING_STABLE_CYCLES
#define APP_CONTROL_LEARNING_STABLE_CYCLES 150u
#endif

#ifndef APP_CONTROL_LEARNING_SETTLE_BAND_PA
#define APP_CONTROL_LEARNING_SETTLE_BAND_PA 2.0f
#endif

#ifndef APP_CONTROL_LEARNING_MAX_DERIVATIVE_PA_PER_S
#define APP_CONTROL_LEARNING_MAX_DERIVATIVE_PA_PER_S 2.0f
#endif

#ifndef APP_CONTROL_LEARNING_FEEDFORWARD_ALPHA
#define APP_CONTROL_LEARNING_FEEDFORWARD_ALPHA 0.05f
#endif

#ifndef APP_CONTROL_LEARNING_STEP_UP_PERCENT
#define APP_CONTROL_LEARNING_STEP_UP_PERCENT 0.08f
#endif

#ifndef APP_CONTROL_LEARNING_STEP_DOWN_PERCENT
#define APP_CONTROL_LEARNING_STEP_DOWN_PERCENT 0.12f
#endif

#ifndef APP_CONTROL_GAIN_SCALE_MIN
#define APP_CONTROL_GAIN_SCALE_MIN 0.35f
#endif

#ifndef APP_CONTROL_GAIN_SCALE_MAX
#define APP_CONTROL_GAIN_SCALE_MAX 1.0f
#endif

#ifndef APP_CONTROL_GAIN_SCALE_GROWTH
#define APP_CONTROL_GAIN_SCALE_GROWTH 0.0025f
#endif

#ifndef APP_CONTROL_GAIN_SCALE_SHRINK
#define APP_CONTROL_GAIN_SCALE_SHRINK 0.025f
#endif

#ifndef APP_CONTROL_INTEGRAL_LIMIT_PA_S
#define APP_CONTROL_INTEGRAL_LIMIT_PA_S 120.0f
#endif

#ifndef APP_CONTROL_INTEGRAL_DECAY_ON_SIGN_FLIP
#define APP_CONTROL_INTEGRAL_DECAY_ON_SIGN_FLIP 0.55f
#endif

#ifndef APP_OTA_STAGING_OFFSET_BYTES
#define APP_OTA_STAGING_OFFSET_BYTES (2u * 1024u * 1024u)
#endif

#ifndef APP_OTA_STAGING_SIZE_BYTES
#define APP_OTA_STAGING_SIZE_BYTES (1536u * 1024u)
#endif

#ifndef APP_OTA_TARGET_MAX_IMAGE_SIZE_BYTES
#define APP_OTA_TARGET_MAX_IMAGE_SIZE_BYTES APP_OTA_STAGING_OFFSET_BYTES
#endif

#ifndef APP_OTA_APPLY_TASK_STACK_WORDS
#define APP_OTA_APPLY_TASK_STACK_WORDS 2048u
#endif

#ifndef APP_OTA_APPLY_TASK_PRIORITY
#define APP_OTA_APPLY_TASK_PRIORITY (APP_WIFI_TASK_PRIORITY + 1u)
#endif

#ifndef APP_OTA_APPLY_DELAY_MS
#define APP_OTA_APPLY_DELAY_MS 500u
#endif

#ifndef APP_LINE_SYNC_TIMEOUT_US
#define APP_LINE_SYNC_TIMEOUT_US 100000u
#endif

#ifndef APP_FAN_FLOW_COEFFICIENT_C
#define APP_FAN_FLOW_COEFFICIENT_C 236.0f
#endif

#ifndef APP_FAN_FLOW_EXPONENT_N
#define APP_FAN_FLOW_EXPONENT_N 0.60f
#endif

#endif
